language: node_js

node_js:
  - 8

install: true

script:
  - find ./public_html -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.designsyst.nichost.ru/home/designsyst/designsystemsclub.ru/docs/{} \;
