language: node_js

node_js:
  - 8

install: true

script:
  - cd public_html && find . -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.designsyst.nichost.ru/designsystemsclub.ru/docs/{} \;
