language: node_js

node_js:
  - 8

install: true

before_script:
  - npm install

script:
  - npm run build
  - chmod -R 777 public_html
  - cd public_html && find . -type f -exec curl --ftp-create-dirs -T {} -u $FTP_USER:$FTP_PASSWORD ftp://ftp.designsyst.nichost.ru/home/designsyst/{} \;
